dist: trusty
sudo: required

language:
    - c++

jobs:
  include:
    - stage: Check code style
      script: bash scripts/ci/ci_check.bash
      language: c++
      git:
        depth: 2
        submodules: false

    - stage: test
      script: bash scripts/install/install_deps.bash
      script: bash scripts/ci/ci_run.bash
      language: c++
      compiler: gcc
      cache:
        ccache: true

notifications:
  email: false
