dist: trusty
sudo: required

language:
    - c++

cache:
    - apt

install:
    - sudo bash scripts/install/install_deps.bash

script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make

notifications:
    recipients:
        - chutsu@gmail.com
    email:
        on_success: change
        on_failure: always
