dist: trusty
sudo: required

language:
    - c++

cache:
    ccache: true
    directories:
        - /usr/local/src

install:
    - sudo bash scripts/install/install_deps.bash

script:
    - bash scripts/ci_run.bash

notifications:
    slack:
        rooms: 
            - wavelabteam:4t8bdaWVBZ5HtHvFhyewStty
        on_success: change
        on_failure: always
    email: false
