dist: trusty
sudo: false

language: cpp

cache:
  ccache: true

env:
  CXX_COMPILER='g++-5'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:lkoppel/robotics'
    packages:
      - g++-5
      - libboost-dev
      - libyaml-cpp-dev
      - libeigen3-dev
      - libpcl-dev
      - libopencv-dev
      - libceres-dev
      - libkindr-dev
      - clang-format-3.8

before_script:
  - export CXX=$CXX_COMPILER  # override travis default
  - bash scripts/ci/ci_check.bash

script:
  - bash scripts/ci/ci_run.bash

notifications:
  email: false
