dist: trusty
sudo: required

language:
    - c++

cache:
    ccache: true


jobs:
  include:
    - stage: install_deps
      script: bash scripts/install/install_deps.bash
    - stage: test
      compiler: clang
      script: bash scripts/ci/ci_run.bash

before_install:
    - bash scripts/ci/ci_check.bash

notifications:
    email: false